-- Seed products
INSERT OR IGNORE INTO products (id, name, description, image, features, category) VALUES
(1, 'RF Signal Analyzer Pro', 'High-performance RF signal analyzer with frequency range from 9kHz to 44GHz. Features real-time spectrum analysis, advanced triggering, and intuitive touchscreen interface.', 'https://source.unsplash.com/random/400x300/?electronics,analyzer', '["9kHz-44GHz range","Real-time analysis","Advanced triggering","Touchscreen interface"]', 'Test Equipment'),
(2, 'Wideband Antenna Array', 'Configurable antenna array system for beamforming applications. Supports multiple frequency bands and can be customized for various deployment scenarios.', 'https://source.unsplash.com/random/400x300/?antenna,array', '["Configurable elements","Multiple frequency bands","Beamforming capability","Weatherproof design"]', 'Antennas');

-- Seed projects
INSERT OR IGNORE INTO projects (id, title, summary, description, image, technologies, category, results) VALUES
(1, '5G Antenna Array for Urban Deployment', 'Advanced 5G antenna array design for high-density urban environments', 'This project involved the design and implementation of a compact MIMO antenna array for 5G infrastructure deployment in dense urban environments. The solution achieved excellent coverage while minimizing visual impact and power consumption.', 'https://source.unsplash.com/random/800x600/?antenna,5g', '["5G","MIMO","Antenna Array","Urban RF Propagation"]', 'Telecommunications', 'The deployed antenna arrays increased network capacity by 300% while reducing energy consumption by 25% compared to traditional solutions.'),
(2, 'Automotive Radar System for ADAS', 'High-resolution radar system for advanced driver assistance systems', 'Developed a 77 GHz FMCW radar system for automotive applications with enhanced resolution and range capabilities. The system was designed to detect and classify multiple objects in complex traffic scenarios for advanced driver assistance systems.', 'https://source.unsplash.com/random/800x600/?radar,automotive', '["77 GHz FMCW Radar","Signal Processing","ADAS","Object Classification"]', 'Automotive', 'The radar system achieved 0.5° angular resolution and 15cm range resolution, significantly improving obstacle detection in poor visibility conditions.');
