#!/bin/bash

echo "====================================================================="
echo "                RF SOLUTIONS WEB APPLICATION DEMO                    "
echo "====================================================================="
echo ""
echo "This script will start the RF Solutions web application server."
echo "The server will run with mock data, no database connection required."
echo ""
echo "After starting, you can access the demo at:"
echo "http://localhost:5000"
echo ""
echo "Available API endpoints:"
echo "- GET /api/projects               (List all projects)"
echo "- GET /api/projects/categories    (List project categories)"
echo "- GET /api/projects/1             (Get specific project details)"
echo "- GET /api/products               (List all products)"
echo "- GET /api/products/categories    (List product categories)"
echo "- POST /api/contacts              (Submit contact form)"
echo ""
echo "Press Ctrl+C to stop the server when finished."
echo ""
echo "Starting server..."
echo "====================================================================="

cd "$(dirname "$0")/server" && node src/index.js