name: Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required to checkout code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
    
    - name: Install client dependencies and build
      run: |
        cd client
        npm ci
        npm run build
    
    - name: Install server dependencies
      run: |
        cd server
        npm ci
    
    - name: Copy client build to server
      run: |
        mkdir -p server/public
        cp -r client/build/* server/public/
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        auth-type: oidc  # Use OpenID Connect for federated authentication
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: ./server
